# Generated by Django 5.2.13 on 2026-04-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='last_name',
        ),
    ]
