# Generated by Django 5.2.13 on 2026-04-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0002_rename_first_name_rider_name_remove_rider_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
