# Generated by Django 5.2.13 on 2026-04-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0003_alter_rider_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
