# Generated by Django 5.2.13 on 2026-04-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0004_alter_race_date_alter_rider_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='category',
            field=models.CharField(choices=[('classic', 'Classic'), ('high_mountain', 'High Mountain'), ('flat', 'Flat')], max_length=50),
        ),
    ]
