# Generated by Django 5.2.13 on 2026-04-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0005_alter_race_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='category',
            field=models.CharField(choices=[('classic', 'Classic'), ('high_mountain', 'High Mountain'), ('flat', 'Flat')], default='classic', max_length=50),
        ),
    ]
