# Generated by Django 5.2.13 on 2026-04-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0006_course_end_course_start_alter_course_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='key_point',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
