# Generated by Django 5.2.13 on 2026-04-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0007_course_key_point_course_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='profile_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='category',
            field=models.CharField(choices=[('classic', 'Classic'), ('high_mountain', 'High Mountain'), ('flat', 'Flat'), ('tour', 'Tour'), ('weekly', 'Weekly')], default='classic', max_length=50),
        ),
    ]
