# Generated by Django 5.2.13 on 2026-04-21 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0008_course_profile_score_rider_note_alter_race_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='predict_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_predict_winner', to='uci.rider'),
        ),
        migrations.AddField(
            model_name='course',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_winner', to='uci.rider'),
        ),
        migrations.AddField(
            model_name='race',
            name='predict_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race_predict_winner', to='uci.rider'),
        ),
        migrations.AddField(
            model_name='race',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race_winner', to='uci.rider'),
        ),
    ]
