# Generated by Django 5.2.13 on 2026-04-21 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0010_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='form',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
