# Generated by Django 5.2.13 on 2026-04-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0011_rider_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
