# Generated by Django 5.2.13 on 2026-04-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0012_alter_rider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='one_day_race',
            field=models.BooleanField(default=False),
        ),
    ]
