# Generated by Django 5.2.13 on 2026-04-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0013_race_one_day_race'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rider',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='rider',
            name='choice',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('increase', 'Increase'), ('normal', 'Normal'), ('decrease', 'Decrease'), ('low', 'Low')], max_length=10, null=True),
        ),
    ]
