# Generated by Django 5.2.13 on 2026-04-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0014_alter_rider_options_rider_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='choice',
        ),
        migrations.AddField(
            model_name='rider',
            name='form_trend',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('increase', 'Increase'), ('normal', 'Normal'), ('decrease', 'Decrease'), ('low', 'Low')], default='normal', max_length=10, null=True),
        ),
    ]
