# Generated by Django 5.2.13 on 2026-04-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0015_remove_rider_choice_rider_form_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='breakaway',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rider',
            name='breakaway_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='form_trend',
            field=models.CharField(blank=True, choices=[('high', '↑'), ('increase', '↗'), ('normal', '→'), ('decrease', '↘'), ('low', '↓')], default='normal', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
