# Generated by Django 5.2.13 on 2026-04-27 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0016_rider_breakaway_rider_breakaway_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderFormHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.IntegerField()),
                ('form_trend', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_history', to='uci.rider')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
