# Generated by Django 5.2.13 on 2026-04-27 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0017_riderformhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderformhistory',
            name='form',
        ),
        migrations.RemoveField(
            model_name='riderformhistory',
            name='form_trend',
        ),
    ]
