# Generated by Django 5.2.13 on 2026-04-27 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0018_remove_riderformhistory_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderformhistory',
            name='form',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
