# Generated by Django 5.2.13 on 2026-04-27 01:59

from django.db import migrations


def init_form_history(apps, schema_editor):
    Rider = apps.get_model('uci', 'Rider')
    RiderFormHistory = apps.get_model('uci', 'RiderFormHistory')
    for rider in Rider.objects.filter(form__isnull=False):
        RiderFormHistory.objects.create(rider=rider, form=rider.form)


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0019_riderformhistory_form'),
    ]

    operations = [
        migrations.RunPython(init_form_history, migrations.RunPython.noop),
    ]
