# Generated by Django 5.2.13 on 2026-05-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0020_init_rider_form_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pre_analysis',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
