# Generated by Django 5.2.13 on 2026-05-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0021_course_pre_analysis_course_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='url',
            new_name='course_url',
        ),
        migrations.AddField(
            model_name='race',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
