# Generated by Django 5.2.13 on 2026-05-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0022_rename_url_course_course_url_race_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_won_by_breakaway',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='profile_score_20k',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
