# Generated by Django 5.2.13 on 2026-05-07 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0024_rider_score_climb_rider_score_puncher_rider_score_tt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='score_puncher',
            new_name='score_punch',
        ),
        migrations.AddField(
            model_name='rider',
            name='score_sprint',
            field=models.FloatField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
