# Generated by Django 5.2.13 on 2026-05-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0025_rename_score_puncher_rider_score_punch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bingo_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
