# Generated by Django 5.2.13 on 2026-06-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0029_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='bet_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='credit_return',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
