# Generated by Django 5.2.13 on 2026-06-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0030_bet_bet_amount_bet_credit_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='credit',
            field=models.FloatField(default=0),
        ),
    ]
