# Generated by Django 5.2.13 on 2026-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0031_alter_userprofile_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
