# Generated by Django 5.2.13 on 2026-06-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0032_alter_userprofile_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='settled',
            field=models.BooleanField(default=False),
        ),
    ]
