# Generated by Django 5.2.13 on 2026-06-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0033_course_settled'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='form_history_cache',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
