# Generated by Django 5.2.13 on 2026-08-13 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0034_rider_form_history_cache'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['-date']},
        ),
    ]
