# Generated by Django 5.2.13 on 2026-09-15 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0035_alter_race_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='limit_distance',
            field=models.FloatField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='limit_slope',
            field=models.FloatField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='score_steep',
            field=models.FloatField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='rider',
            name='score_climb',
            field=models.FloatField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='rider',
            name='score_punch',
            field=models.FloatField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='rider',
            name='score_sprint',
            field=models.FloatField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='rider',
            name='score_tt',
            field=models.FloatField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='rider',
            name='score_wave',
            field=models.FloatField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
