# Generated by Django 5.2.7 on 2026-09-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0037_alter_rider_score_climb_alter_rider_score_punch_and_more'),
    ]

    operations = [
        # Existing key_point values are free-text (not valid JSON). Wrap each as
        # a JSON string so it survives the JSON_VALID CHECK constraint added by
        # the field alter below; empty strings become NULL.
        migrations.RunSQL(
            sql=[
                "UPDATE uci_course SET key_point = NULL WHERE key_point = '';",
                "UPDATE uci_course SET key_point = json_quote(key_point) "
                "WHERE key_point IS NOT NULL;",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='course',
            name='key_point',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
