# Generated by Django 5.2.13 on 2026-09-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0038_alter_course_key_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_summary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
