# Generated by Django 5.2.13 on 2026-09-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0039_course_course_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='attack_index',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
