# Generated by Django 5.2.13 on 2026-09-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0040_rider_attack_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='watch_listed',
            field=models.BooleanField(default=False),
        ),
    ]
