# Generated by Django 6.0.8 on 2026-09-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uci', '0041_rider_watch_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='date_duration_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='form_duration',
            field=models.IntegerField(blank=True, default=14, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='pre_analysis',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
